### ISSUE TITLE
Some expressions still in english only

### ISSUE THREAD

**Issue by ahouin** [pancakeapp/translations#45]
A made some screenshots of expressions that haven't been translated yet. I didn't go through all the pages, there could be some untranslated expressions left.

Page : All invoices
![pancake1](https://cloud.githubusercontent.com/assets/1697415/4180320/356b0f86-36f3-11e4-8ba9-b7f207c63818.jpg)

Page : Edit an invoice
![pancake2](https://cloud.githubusercontent.com/assets/1697415/4180325/88a23044-36f3-11e4-836d-e5e7e573a7b7.jpg)

Page : Timesheet
![pancake3](https://cloud.githubusercontent.com/assets/1697415/4180326/98319a72-36f3-11e4-960f-22f6fea5f4b1.jpg)

Page : Search Results
![pancake4](https://cloud.githubusercontent.com/assets/1697415/4180330/a8ee8bcc-36f3-11e4-8e16-a7a65fc384f5.jpg)

Page : Reminders
![pancake5](https://cloud.githubusercontent.com/assets/1697415/4180333/d6e70626-36f3-11e4-8b4a-756afcf8c817.jpg)

Page : All Estimates
![pancake6](https://cloud.githubusercontent.com/assets/1697415/4180334/e57f4d6a-36f3-11e4-9ba2-5e2e3e1c2b09.jpg)

Page : All Projects
![pancake7](https://cloud.githubusercontent.com/assets/1697415/4180337/ef008b9c-36f3-11e4-97c9-58b0963438af.jpg)

Page : Add Expense
![pancake8](https://cloud.githubusercontent.com/assets/1697415/4180339/f9616b6a-36f3-11e4-8337-f0dec92a07ae.jpg)

Page : Add Supplier (Expense)
![pancake9](https://cloud.githubusercontent.com/assets/1697415/4180341/0777917a-36f4-11e4-8025-492fd448200a.jpg)

Page : Add Category (Expense)
![pancake10](https://cloud.githubusercontent.com/assets/1697415/4180342/141c1590-36f4-11e4-8e36-024ff34829d1.jpg)

**Comment by BrunoDeBarros** [comment]
All of these have been resolved for the next update to Pancake. As for removing the text-transform, you can add that in Settings > Branding, to your "Backend Custom CSS" (you will need the next update of Pancake for this to work):

.side-bar-btns li a {text-transform: initial;}

**Comment by ahouin** [comment]
Thanks a lot Bruno ! Well done !

**Comment by BrunoDeBarros** [comment]
The only thing we haven't translated is the "assignments" section, because that's all going away as soon as we get the new role-based access control system up and running.
