### ISSUE TITLE
Untranslated parts of pages

### ISSUE THREAD

**Issue by pprazzi** [pancakeapp/translations#57]
Here a bunch of pages where I've marked some missing translations. 

I hope this helps

![users___](https://cloud.githubusercontent.com/assets/3692684/5634354/41032ae0-95df-11e4-8848-199631698f96.png)
![projects_ _view___](https://cloud.githubusercontent.com/assets/3692684/5634356/412147dc-95df-11e4-9cf1-533e986cf967.png)
![projects___](https://cloud.githubusercontent.com/assets/3692684/5634360/413015f0-95df-11e4-90a7-f6d5081863fa.png)
![invoices_ _create___](https://cloud.githubusercontent.com/assets/3692684/5634359/412d1f80-95df-11e4-9ec5-941833c9849c.png)
![invoices_ _create____1](https://cloud.githubusercontent.com/assets/3692684/5634355/4120aa2a-95df-11e4-8db6-2102896db1e1.png)
![invoices___](https://cloud.githubusercontent.com/assets/3692684/5634358/4125fa5c-95df-11e4-9671-9a30d1a418e1.png)
![clients___](https://cloud.githubusercontent.com/assets/3692684/5634357/4122fa1e-95df-11e4-927e-aafcd44ef7fe.png)
![clients____1](https://cloud.githubusercontent.com/assets/3692684/5634361/41343a86-95df-11e4-9243-b90169a41057.png)

**Comment by pprazzi** [comment]
![expenses_ _suppliers___](https://cloud.githubusercontent.com/assets/3692684/5644142/b88ae220-9660-11e4-954f-45349b8e8018.png)
![expenses_ _categories___](https://cloud.githubusercontent.com/assets/3692684/5644143/b88b890a-9660-11e4-819f-53931ad56baf.png)
![expenses___](https://cloud.githubusercontent.com/assets/3692684/5644144/b88bc640-9660-11e4-9ee2-a4f5123bf017.png)

**Comment by pprazzi** [comment]
![onbetaalde_facturen___](https://cloud.githubusercontent.com/assets/3692684/5644203/547e203e-9661-11e4-8ec8-9acb1f49ce89.png)

**Comment by pprazzi** [comment]
![betalingen___](https://cloud.githubusercontent.com/assets/3692684/5644226/941c817c-9661-11e4-97a9-9853e57ed90b.png)

**Comment by BrunoDeBarros** [comment]
Thanks Jan! I'll get these all into Pancake in the next couple of days.

**Comment by pprazzi** [comment]
Thanks

**Comment by ahouin** [comment]
Here's some translations other missing translations
![edit user](https://cloud.githubusercontent.com/assets/1697415/6149921/18214d34-b1da-11e4-8934-88ecbcd30c9c.jpg)

**Comment by ahouin** [comment]
As well as these
![discussion](https://cloud.githubusercontent.com/assets/1697415/6150259/53bf698c-b1dc-11e4-9d3c-f5ba52ed47d5.jpg)
![ticket](https://cloud.githubusercontent.com/assets/1697415/6150263/59c1bd9e-b1dc-11e4-9155-abae5bbadd73.jpg)

**Comment by BrunoDeBarros** [comment]
All done! It'll be in the next Pancake update. :)

The only one we haven't done here is the "Are you sure you want to leave this page?" thing. That's the browser, it's not controlled by Pancake.

**Comment by BrunoDeBarros** [comment]
Another thing I haven't yet resolved is the "19 hours and 44 minutes ago". That's going to require us changing the way our date formatting code works, and it might still take a bit. I think this can be done using locales in PHP, so that you don't have to write any translations.
