### ISSUE TITLE
NEWS: Integration with Pancake and third-party translation service!

### ISSUE THREAD

**Issue by BrunoDeBarros** [pancakeapp/translations#61]
I have something to tell you all: We're going to integrate a third-party translation service with Pancake, so that any changes we make to the English language file will automatically be translated by them and then sent back to us. We'll have a system in place to automatically commit their translations to this repository, and we'll have a system in place to automatically merge this repository in with the main repository whenever we launch updates. So all of the languages here will soon be included in Pancake and automatically updated with every release.

What that means for you is that when we do that, all of your translations will be kept up to date automatically by the translation service we're using, which should save you a lot of time. If you spot any translation you disagree with or wanna correct something, you're still able to create pull requests as usual, and we'll still merge them as usual. They will then be included in the next Pancake release and distributed to the thousands of people who use Pancake every day. You'll be helping everyone who uses Pancake in a language other than English.

This translation service was the last thing we needed to integrate this repository with Pancake (otherwise we'd run the risk of releasing updates with outdated languages, like Brazilian, which hasn't seen an update since the Pancake 4.3 days). I'm really glad we're finally going to do this. There'll be a bunch of new languages as well, in addition to the ones we already have. It'll be brilliant.

If you have any thoughts on this, just let me know! :smile:

CC @ahouin @mamarmite @fucx @dospuntocero @jeffreybertoen @pprazzi @peterruiter @robsonsobral @davidh071 @carstengrimm @anas10 @ghost @therephil

**Comment by ahouin** [comment]
That's great news right there ! I'm looking forward to see it included in Pancake soon !

**Comment by pprazzi** [comment]
:thumbsup: good news

**Comment by jeffreybertoen** [comment]
Yes this is really awesome, no more typo's from me anymore :P

**Comment by davidh071** [comment]
Nice, Your reply to all function...

Met vriendelijke groet,
David van Hoven

@davidh071 <http://www.twitter.com/davidh071>

Why join the navy if you can be a pirate? - Steve Jobs




2015-02-10 15:21 GMT+01:00 jeffreybertoen <notifications@github.com>:

**Comment by dospuntocero** [comment]
amazing :D

--




[image: dospuntocero]

*Francisco Javier Arenas Ulloa*
Front-end Developer, dospuntocero ltda.
Tel: (56) 032 - 328 01 94 | Cel: (56) 09 - 9352 7553
Nieto 93, Viña del Mar <http://g.co/maps/km5ue>
www.dospuntocero.cl | visítanos en facebook
<http://facebook.com/dospuntocero.cl>

2015-02-10 11:21 GMT-03:00 jeffreybertoen <notifications@github.com>:

**Comment by anas10** [comment]
Great news!
