### ISSUE TITLE
Non localized strings

### ISSUE THREAD

**Issue by joapalmer** [pancakeapp/translations#66]
Here are a bunch of unlocalized strings in Pancake, version 4.7.12

* File:  /third_party/themes/pancake/views/modules/kitchen/new_ticket.php
   AND
   /third_party/themes/pancake/views/modules/kitchen/tickets.php
   Line 2: "Support tickets" not a localized string. Cannot be translated.

* Also /third_party/themes/pancake/views/modules/kitchen/tickets.php has other unlocalized strings.

* The menu button title "Dashboard" in
  /third_party/themes/pancake/views/layouts/kitchen.php
  at line 67 is not a localized string, so it cannot be translated.

* The title "Dashboard" in
  /third_party/themes/admin/pancake/views/modules/dashboard/dashboard.php
  line 4

* /third_party/themes/admin/pancake/views/modules/projects/_projects_list.php
  The title at line 8
  AND Quick add input label at line 53

**Comment by BrunoDeBarros** [comment]
Thanks, @joapalmer, these have all been resolved for the next update of Pancake! :smile:
