### ISSUE TITLE
French Translation Updated

### ISSUE THREAD

**Issue by BrunoDeBarros** [pancakeapp/translations#71]
@ahouin and @damiendd I've had the French translation updated with stuff from 4.8.11 (yet to be released). If you want to, feel free to look it over and let me know what you think.

The file is automatically reformatted (and the authors are all added to the top of the file), to avoid complications.

I've also added tests to make sure that pull requests no longer cause parse errors, like what happened with @ahouin's latest pull request. Now I'll only merge them when Travis says they don't have problems.

Also, a warning: This translation will be included in Pancake 4.8.11, and it'll be kept up to date automatically with the contents from this repo. So if you wanna make changes, don't edit the files in your installation - edit them here and the changes will be in the next update. You no longer need to worry about manually updating your installations.

**Comment by ahouin** [comment]
So do we have do something with the translations at the bottom of the file ?

**Comment by BrunoDeBarros** [comment]
The English file will remain the same, so you can still pull up the changes from the bottom of the file, in that `# begin v4.8.x changes` section, and add the changes to the French file like you've been doing. Nothing much changes for you. However, our system now reformats and reorganizes the file automatically when adding new translations, so it's a bit different now. Just check out the current version of the file; you'll see the differences.

However, it is worth noting that we'll always have all the translations up-to-date any time we release an update. And the updated translations will automatically be included with Pancake updates, so you'll never have to worry again - you don't need to translate anything.

**We still need your help though.** If you spot anything that doesn't sound right or you just want to improve the translation for anything, feel free to change stuff and we'll merge your changes.

Another note: Author information is pulled up from GitHub and added to the file automatically, so you now show up in the file's copyright comment. It pulls your email and your URL from whatever you've set it as in GitHub - if you don't have a public email address in GitHub or you don't have a URL, then none will be added.
