### ISSUE TITLE
Error with settings:hide_tax_column_explanation'

### ISSUE THREAD

**Issue by BrunoDeBarros** [pancakeapp/translations#75]
In English, it says:

> This will hide the tax column in invoices that have no tax information.

In French, it says:

> Ceci cachera la colonne des taxes sur les factures.

This is incorrect. @ahouin, you were the one who wrote this initially; would you be willing to look into this? I presume it should be something like (not a native speaker, so forgive me if it's wrong):

> Ceci cachera la colonne des taxes sur les factures qui ont pas de détails de taxes.

**Comment by ahouin** [comment]
You're right @BrunoDeBarros . It should be : Ceci cachera la colonne des taxes sur les factures qui n'ont pas de détails de taxes.

I only add " n' " to " ont "
