### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Julien76** [pancakeapp/translations#90]
Hi,

The word to translate "estimate" in French is quite odd. It is right now "soumission", which is weird way to formulate it and being French I never heard of it for the equivalent of "estimate" in business.

I think "devis" is a better word. I made the change locally in my installation. If interested, I can make a pull request.

**Comment by BrunoDeBarros** [comment]
Absolutely, make a PR. 

@ahouin You've been maintaining the French translation; what are your thoughts on this?

**Comment by ahouin** [comment]
@Julien76 is absolutely right. I wasn't sure wich word to use when I translated this expression. I will update this in the language file.

**Comment by Julien76** [comment]
Hi,

Sorry I'm a bit short on time after to do it properly, but if that helps, here is the file I modified on my set-up with all the "soumission" replaced by "devis".

As I can't upload php file, I have renamed the extension to txt. Renaming it back to php should do.

[pancake_lang.txt](https://github.com/pancakeapp/translations/files/1270981/pancake_lang.txt)

**Comment by BrunoDeBarros** [comment]
There's a number of improvements to this updated file that should be reviewed before merging. It's not just the Devis changes.

@ahouin If you want I can create a PR for this, but it seems like it might just be easier for you to grab this .txt file, rename it to .php and drop it in the repo and go through the diff to decide what you want to change / keep.

**Comment by ahouin** [comment]
@BrunoDeBarros What about switching directly "soumission" for "devis" in the pancake_lang.php already there?

**Comment by Julien76** [comment]
You cannot directly, the grammar will be incorrect.
"Soumission" is a feminine word while "devis" is masculine.
You will need to change as well:
"Une" for "un"
"La" for "le"
"De la" for "Du"
"Cette" for "Ce"
In front of all occurrences.

**Comment by ahouin** [comment]
@Julien76 This is what I meant. Replacing the word as well as the correct expression.

J'avais mis devis au tout début mais j'ai finalement tout changer pour soumission donc j'ai dû rechanger les expressions. Je vais le refaire à nouveau.

**Comment by Julien76** [comment]
@ahouin

Dans le fichier txt envoyé, j'ai déjà corrigé la grammaire si ça peut t'aider.

**Comment by Julien76** [comment]
One thing maybe to keep in mind, "Soumission" might be more correct for the French speaking Canadian. It could be worth to check. If that's the case, then we could have Fr_Fr and Fr_Ca as two separate languages.

**Comment by ahouin** [comment]
That's why I wasn't sure wich word to use. Proposal as well let me ambivalent.

**Comment by ahouin** [comment]
@Julien76 @BrunoDeBarros 

I've updated the french language file to v4.13.7 and switched "soumission" for "devis".

**Comment by BrunoDeBarros** [comment]
Thanks to you both, you're awesome! 😃 If there's anything I can do to make the French translation better/easier to maintain, just let me know.
