### ISSUE TITLE
Did Pancake Die?

### ISSUE THREAD

**Issue by palomnik** [pancakeapp/translations#93]
I suddenly had an issue that breaks pancake and requires a manual update.  I have
suddenly found that the domain no longer exists and I can't access the site or email support.

Is this a temporary glitch or has Pancake pulled the plug without telling anyone?

Way to communicate with customers!

**Comment by BrunoDeBarros** [comment]
Hey John,

I'm sorry for the trouble - The project is not dead; there is an ongoing issue with our hosting service that we're looking to resolve as quickly as possible. You can email me at bruno@greyappsgroup.com to sort out your update issues.

**Comment by palomnik** [comment]
OK, you gave me a heart attack!  There is no other good solution like 
pancake.

When I  came back, the site was already back up, and the manual update 
was easily accomplished.

A word of advice - you have a twitter account: please send a tweet to 
let people know what is happening so that they don't pull their hair out!

Thanks,

John

**Comment by BrunoDeBarros** [comment]
@palomnik I fully agree with you. I don't have access to our Twitter, unfortunately, so wasn't able to provide information on the matter. It's good you reached out here; I can be reached at support@greyappsgroup.com as well if you ever find yourself needing to contact me again outside of @pancakeapp.com.
