### ISSUE TITLE
Dutch string effects layout

### ISSUE THREAD

**Issue by sprucify** [pancakeapp/translations#95]
login:username_email in Dutch is too long and deforms login screen

**Comment by BrunoDeBarros** [comment]
Thank you! What would you change it to, any suggestions?

**Comment by sprucify** [comment]
'login:username_email' => 'Gebruikersnaam / Email', to 'login:username_email' => 'Email',

**Comment by BrunoDeBarros** [comment]
Thanks @sprucify I've sorted it out, and it'll be included in the next update to Pancake!
